{% set version = "2.0.0" %}

package:
  name: cffi
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/c/cffi/cffi-{{ version }}.tar.gz
  sha256: 44d1b5909021139fe36001ae048dbdde8214afa20200eda0f64c068cac5d5529
  patches:
    - 0001-Link-to-dl-library.patch
    - 0002-setup-linux.patch
    - 0003-apple-api.patch  # [osx]

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - patch     # [not win]
    - m2-patch  # [win]
  host:
    - python
    - pip
    - wheel
    - setuptools >=66.1
    - libffi  # [not win]
    - pycparser
  run:
    - python
    - libffi  # [not win]
    - pycparser

test:
  imports:
    - cffi
    - _cffi_backend
  requires:
    - pip
    - openssl *
  commands:
    - pip check
    - python -X faulthandler -c "from cffi import FFI; print(FFI().dlopen('ucrtbase'))"  # [win]
    - python -X faulthandler -c "from cffi import FFI; print(FFI().dlopen(None))"  # [not win]

about:
  home: https://github.com/python-cffi/cffi
  license: MIT
  license_file: LICENSE
  summary: Foreign Function Interface for Python calling C code.

  description: |
    Cffi aims to allow users to call C code from Python without having to
    learn a 3rd language. It provides a convenient and reliable way to call
    compiled C code from Python using interface declarations written in C.
  doc_url: https://cffi.readthedocs.io
  dev_url: https://github.com/python-cffi/cffi

extra:
  recipe-maintainers:
    - goanpeca
    - ocefpaf
    - katietz
    - h-vetinari
